### ISSUE TITLE
Issue building barebones

### ISSUE THREAD

**Issue by sandord** [ggnkua/bigbrownbuild-git#1]
First of all, I'd like to say that I'm really glad that this project exists.

After successfully running `bigbrownbuild.sh`, I tried to do `make` in the `barebones` directory.

This however, led to the following error:

    /brown/bin/m68k-atariextrabrowner-elf-gcc -c -m68000 -Ofast -fomit-frame-pointer -fstrict-aliasing -fcaller-saves -flto
         -ffunction-sections -fdata-sections -fleading-underscore -D__ATARI__ -D__M68000__ -DELF_CONFIG_STACK=16384
         -Wall -o vsnprint.o vsnprint.c
    make: /brown/bin/m68k-atariextrabrowner-elf-gcc: Command not found
    make: *** [Makefile:233: vsnprint.o] Error 127

After checking the `/brown/bin` directory, I found that the binaries were all called `m68k-atarisuperbrowner-*` instead.

So I naively updated the `Makefile` to refer to `super` instead of `extra`.

This led to another error:

    /brown/bin/m68k-atarisuperbrowner-elf-g++ -c -m68000 -Ofast -fomit-frame-pointer -fstrict-aliasing -fcaller-saves -flto -ffunction-sections -fdata-sections -fleading-underscore -D__ATARI__ -D__M68000__ -DELF_CONFIG_STACK=16384   -x c++ -std=c++0x -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wall -Wno-reorder -o lolworld.o lolworld.cpp
    /brown/bin/m68k-atarisuperbrowner-elf-g++ -L/brown/lib/gcc/m68k-atarisuperbrowner-elf/10.2.0/m68000 -L/brownm68k-atarisuperbrowner-elf/lib/m68000 -o lolworld.elf  libcxx/brownboot.o libcxx/browncrti.o libcxx/browncrt++.o libcxx/zerolibc.o libcxx/zerocrtfini.o vsnprint.o printf.o  lolworld.o -Wl,-Map,lolworld.map -Wl,--emit-relocs -Wl,-e_start -Ttext=0 -nostdlib -nostartfiles -m68000 -Ofast -fomit-frame-pointer -fstrict-aliasing -fcaller-saves -flto -ffunction-sections -fdata-sections -fleading-underscore  libcxx/browncrtn.o
    lto1: fatal error: bytecode stream in file 'libcxx/browncrt++.o' generated with LTO version 9.0 instead of the expected 11.0
    compilation terminated.
    lto-wrapper: fatal error: /brown/bin/m68k-atarisuperbrowner-elf-g++ returned 1 exit status
    compilation terminated.
    /brown/lib/gcc/m68k-atarisuperbrowner-elf/11.2.0/../../../../m68k-atarisuperbrowner-elf/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:188: lolworld.elf] Error 1
    rm lolworld.o

Apparently LTO version 9.0 is being used instead of the expected 11.0.

I have no idea how to fix this. Do you have any ideas? Thanks!

**Comment by ggnkua** [comment]
Hi there, thanks for the kind words!

Try to delete all .o files from the `libcxx` folder and building. I think this fixes the issue. If not, just let me know and I'll try to remember what else is needed :).

**Comment by sandord** [comment]
Thanks!

As a side note: I'm not experienced with Linux so I might be making basic mistakes here and there. If you don't mind, please point them out to me!

Anyway, I'm trying to get this working on WSL2/Ubuntu.

So here's what I just did:

- `rm libcxx/*.o`
- `make`

      ./vasmm68k_mot.exe -Felf -showcrit -noesc -D__ATARI__ -D__M68000__ -DELF_CONFIG_STACK=16384
         -o libcxx/brownboot.o libcxx/brownboot.s
      make: ./vasmm68k_mot.exe: Command not found
      make: *** [Makefile:249: libcxx/brownboot.o] Error 127

    Apparently I'm missing `vasmm68k_mot` __and__ it's an `.exe` so I compiled vasm, installed it (`sudo cp vasmm68k_mot /usr/bin`) and change `./vasmm68k_mot.exe` in the `Makefile` to `vasmm68k_mot` without the leading `./`.

- `make`

      (...)
      ./brownout.exe -p 0 -i lolworld.elf -o lolworld.tos
      make: ./brownout.exe: Command not found
      make: *** [Makefile:189: lolworld.elf] Error 127
      rm lolworld.o

I must admit I'm not sure where `brownout.exe` is supposed to come from 🤭

**Comment by ggnkua** [comment]
That's the easy bit! Just compile it from this repo: https://github.com/ggnkua/brownout-git

I guess this all points out that I must make an action item to revamp the instructions, and probably merge brownout into this repo.

**Comment by sandord** [comment]
I now have a few `.TOS` / `.PRG` files so it seems to have worked!

I had to change `./brownout.exe` to `brownout` in `Makefile` as well.

Can I ask why there are references to `.exe` files in a `.sh` script? ;-)

**Comment by sandord** [comment]
For reference, here are the steps I took to get the `bigbrownbuild.sh` to build correctly on WSL2 on my machine:

- **Clone the repository**
    
      git clone https://github.com/ggnkua/bigbrownbuild-git

- **Install some dependencies**

      sudo apt install g++
      sudo apt install make
      sudo apt install bison
      sudo apt install flex

  - vasm
    
        curl --output vasm.tar.gz http://sun.hasenbraten.de/vasm/release/vasm.tar.gz
        tar xvf vasm.tar.gz
        make CPU=m68k SYNTAX=mot
        sudo cp vasmm68k_mot /usr/bin

  - brownout
        
        git clone https://github.com/ggnkua/brownout-git
        cd brownout-git
        ./buildit.sh
        sudo cp brown.out /usr/bin/brownout

- **Run the big brown build script**

  From the directory where you cloned the `bigbrownbuild-git` repository:

      sudo bash ./bigbrownbuild.sh

**Comment by ggnkua** [comment]
First of all, nice that you made it work eventually!

As for your question - the Makefile was written on Cygwin, and we never sat down and made all the filenames work across all OSes. Also something to look into...

**Comment by ggnkua** [comment]
Okay, just made some adjustments here and there and I think this should be all. Also, I figured out that if one doesn't remove brownboot.o, the requirement for vasm can be dropped.

Finally, I removed the .o files from the repository so now they will be built first time the barebones build is called.

Hopefully that's all. If I missed anything I guess we'll find out at some point!

**Comment by sandord** [comment]
Thanks a lot for helping me out!

**Comment by ggnkua** [comment]
No problem. Anything else, feel free to ask.

**Comment by sandord** [comment]
I see that you removed a handful of `.o` files in the latest commit. I was wondering, did you leave in the `brownboot.o` file in on purpose?

**Comment by ggnkua** [comment]
Yes, as I said above: brownboot.o is assembled by vasm and isn't going to change whatever version of gcc one uses. So, by keeping the .o file the vasm dependency is dropped.

**Comment by sandord** [comment]
Ah yes, the good old reading skill. Not my strong suit 🙈
