### ISSUE TITLE
It looks like there's a slash missing in barebones/Makefile

### ISSUE THREAD

**Issue by sandord** [ggnkua/bigbrownbuild-git#2]
Hi, it looks like there's a slash missing in here after `-L/brown`:

https://github.com/ggnkua/bigbrownbuild-git/blob/58935072a80c31736c021547d926b76d76e04ec5/barebones/Makefile#L25

Since the build does work, I guess that library path isn't required at all?

**Comment by ggnkua** [comment]
Just tested the build without that path and it (naturally) worked. Thanks for the report, I pushed a fix!
