### ISSUE TITLE
Add texinfo to prerequisites

### ISSUE THREAD

**Issue by n0kturnal** [ggnkua/bigbrownbuild-git#4]
Just to let you know I ran into troubles building binutils 0.39 on Atlassian CI Linux image (Ubuntu Feisty-something-whatever). bigbrownbuild.sh script failed, because during binutils compilation texinfo was required, but missing in system (I reran make in binutils folder to catch this error). Installing texinfo fixed problem (apt-get install texinfo), so it would be cool to add it to prerquisities list.

**Comment by ggnkua** [comment]
Hi there,

First of all, I assume you mean binutils 2.39?

I've definitely run into texinfo related build problems, but it was when I was trying to build the trunk version of gcc. This is the first time I heard that texinfo is required for normal builds. It's not impossible that I have texinfo installed on my distros so I never run into this.

In any case, I'll add a note about this in the readme.md just so people know. Thanks for the report

**Comment by n0kturnal** [comment]
Yes, it's binutils 2.39. And I also didn't have similar issues before. gcc scripts for downloading prerequisites are quite reliable.
