### ISSUE TITLE
13.1.0, 13.2.0 and Trunk binutils version

### ISSUE THREAD

**Issue by paulwratt** [ggnkua/bigbrownbuild-git#5]
starting at [line 216 in bigbrownbuild.sh](https://github.com/ggnkua/bigbrownbuild-git/blob/master/bigbrownbuild.sh#L216C1-L220C1):
```
        if [ "$BUILD_13_1_0" == "1" ] || [ "$BUILD_TRUNK" == "1" ]; then
            if [ ! -f binutils-2.40.tar.xz ]; then rm -rf binutils-2.40; fi; fi
        if [ "$BUILD_13_2_0" == "1" ] || [ "$BUILD_TRUNK" == "1" ]; then
            if [ ! -f binutils-2.40.tar.xz ]; then rm -rf binutils-2.41; fi; fi
```
and based on [line 271 & 272](https://github.com/ggnkua/bigbrownbuild-git/blob/master/bigbrownbuild.sh#L269C1-L273C1):
```
    if [ "$BUILD_13_1_0" == "1" ]; then
        if [ ! -f binutils-2.40.tar.xz ]; then wget http://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz --quiet; fi; fi
    if [ "$BUILD_13_2_0" == "1" ] || [ "$BUILD_TRUNK" == "1" ]; then
        if [ ! -f binutils-2.41.tar.xz ]; then wget http://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz --quiet; fi; fi
```
shouldn't that first piece of code end:
```
        if [ "$BUILD_13_1_0" == "1" ]; then
            if [ ! -f binutils-2.40.tar.xz ]; then rm -rf binutils-2.40; fi; fi
        if [ "$BUILD_13_2_0" == "1" ] || [ "$BUILD_TRUNK" == "1" ]; then
            if [ ! -f binutils-2.41.tar.xz ]; then rm -rf binutils-2.41; fi; fi
```

**Comment by ggnkua** [comment]
I've just pushed a fix for this, thanks!

**Comment by paulwratt** [comment]
sweet

I got into the habit of applying patches manually, in order to try an familiarise myself with any software I use, I guess that extends to everything I use now :)

I am thinking this is what they meant when you read statements like:

> Because it is open source software (OSS), you can review the source yourself

anyway, thanks for the quick turn-around on this
